name: Script quotidien marée et météo dev

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: false
          python-version: "3.10"
          channels: conda-forge

      - name: Installer eccodes via conda
        run: conda install -c conda-forge eccodes -y

      # … tes autres étapes …

      - name: Exécuter le script R
        env:
          CMEMS_USER: ${{ secrets.CMEMS_USER }}
          CMEMS_PWD:  ${{ secrets.CMEMS_PWD }}
          PATH: /usr/share/miniconda/Library/bin:${{ env.PATH }}
        run: |
          Rscript script3.R

          git add zos_points.csv data_meteo.csv || echo "rien à committer"
          git commit -m "Mise à jour quotidienne" || echo "pas de modifications"
          git push
