name: Script quotidien marée et météo

#on:
#  schedule:
#    - cron: '0 0 * * *'   # Tous les jours à 0h UTC
#    - cron: '0 5 * * *'   # Tous les jours à 5h UTC
#    - cron: '0 10 * * *'  # Tous les jours à 10h UTC
#    - cron: '0 15 * * *'  # Tous les jours à 15h UTC
#  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt avec droits push
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances système pour R
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Installer les packages Python nécessaires
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine

      - name: Installer les dépendances système pour terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev

      - name: Installer ECCODES et ses dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libeccodes-tools \
            libeccodes-dev

      - name: Vérifier l'installation d'ECCODES
        run: |
          which grib_copy
          grib_copy -V

      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(c(
            'reticulate','terra','tidyr',
            'httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite','lubridate'
          ), repos='https://cloud.r-project.org')"

      - name: Exécuter le script R
        env:
          CMEMS_USER: ${{ secrets.CMEMS_USER }}
          CMEMS_PWD: ${{ secrets.CMEMS_PWD }}
        run: Rscript script3.R

      # …vos étapes précédentes (checkout, génération des CSV, etc.)…

      - name: Commit des fichiers CSV générés
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Ajout automatique des CSV : hauteurs de mer et données météo" \
            || echo "Aucun changement à committer"
          git push
      
      - name: Push vers dépôt privé maree-donnees
        env:
          DATA_PUSH_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
        run: |
          git clone https://x-access-token:${DATA_PUSH_TOKEN}@github.com/ahulin/maree-donnees.git data-push
          cp zos_points.csv data-push/
          cp data_meteo.csv data-push/
          cd data-push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Mise à jour quotidienne des CSV : hauteurs de mer et données météo" \
            || echo "Pas de changement"
          git push

