name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Version compatible avec reticulate

      - name: Installer les packages Python nécessaires
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine virtualenv

      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(c('reticulate'), repos = 'https://cloud.r-project.org')"

      - name: Exécuter le script R avec reticulate
        run: Rscript script.R
