name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'   # Tous les jours à 6h du matin UTC (8h en France)
  workflow_dispatch:       # Permet aussi de le lancer à la main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer ecCodes et dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-dev libeccodes-tools

      - name: Installer les packages R nécessaires
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            #tidyverse
            #lubridate
            httr
            #rvest
            jsonlite
            # ajoute ici ce que tu veux

      - name: Exécuter le script R
        run: Rscript script.R

