name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'   # Tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    # Permet de lancer chaque 'run:' dans un shell login, 
    # pour que micromamba s’active automatiquement
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # 1) Checkout
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2) Installer R
      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      # 3) Installer Python
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4) Installer micromamba (script officiel)
      - name: Installer micromamba
        run: |
          curl -L micro.mamba.pm/install.sh | bash
      - name: Ajouter micromamba au PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 5) Installer eccodes via micromamba
      - name: Installer eccodes
        run: micromamba install -n base -c conda-forge eccodes -y

      # 6) Vérifier que grib_copy est bien disponible
      - name: Vérifier grib_copy
        run: |
          which grib_copy
          grib_copy --help

      # 7) Dépendances système pour terra + R
      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev libproj-dev libgeos-dev libudunits2-dev \
            libpng-dev

      # 8) Dépendances Python
      - name: Installer copernicusmarine
        run: |
          pip install --upgrade pip
          pip install copernicusmarine

      # 9) Dépendances R
      - name: Installer les packages R
        run: |
          Rscript -e "install.packages(c(
            'reticulate','terra','tidyr',
            'httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite'
          ), repos='https://cloud.r-project.org')"

      # 10) Exposer R_LIBS_USER pour Rscript
      - name: Exposer R_LIBS_USER
        run: |
          R_LIB=$(Rscript -e '.libPaths()[1]' --vanilla)
          echo "R_LIBS_USER=${R_LIB}" >> $GITHUB_ENV

      # 11) Exécution du script R principal
      - name: Exécuter le script R
        env:
          CMEMS_USER:      ${{ secrets.CMEMS_USER }}
          CMEMS_PWD:       ${{ secrets.CMEMS_PWD }}
          DATA_PUSH_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
        run: |
          Rscript script2.R

      # 12) Commit & push sur le dépôt principal
      - name: Commit des CSV générés
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Mise à jour automatique des CSV" || echo "Rien à committer"
          git push

      # 13) Push vers dépôt privé de données
      - name: Push vers maree-donnees
        run: |
          git clone https://x-access-token:${{ secrets.DATA_PUSH_TOKEN }}@github.com/ahulin/maree-donnees.git data-push
          cp zos_points.csv data_meteo.csv data-push/
          cd data-push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Mise à jour quotidienne des CSV" || echo "Rien à committer"
          git push
