name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2) Installer R
      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      # 3) Installer Python
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4) Installer ECCODES et autres libs système
      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libeccodes-tools \
            libgdal-dev libproj-dev libgeos-dev libudunits2-dev \
            libpng-dev

      # 5) Installer copernicusmarine (Python)
      - name: Installer copernicusmarine
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine

      # 6) Installer les packages R
      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(c(
            'reticulate','terra','tidyr',
            'httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite'
          ), repos='https://cloud.r-project.org')"

      # 7) Exposer R_LIBS_USER pour Rscript (pour reticulate, etc.)
      - name: Exposer R_LIBS_USER
        run: |
          R_LIB=$(Rscript -e '.libPaths()[1]' --vanilla)
          echo "R_LIBS_USER=${R_LIB}" >> $GITHUB_ENV

      # 8) Exécuter ton script R
      - name: Exécuter le script R
        env:
          CMEMS_USER:      ${{ secrets.CMEMS_USER }}
          CMEMS_PWD:       ${{ secrets.CMEMS_PWD }}
          DATA_PUSH_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
          # R_LIBS_USER injecté via l'étape précédente
        run: |
          Rscript script3.R

      # 9) Commit + push dans le dépôt principal
      - name: Commit des CSV générés
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Ajout automatique des CSV" || echo "Rien à committer"
          git push

      # 10) Pousser vers le dépôt privé de données
      - name: Push vers maree-donnees
        run: |
          git clone https://x-access-token:${{ secrets.DATA_PUSH_TOKEN }}@github.com/ahulin/maree-donnees.git data-push
          cp zos_points.csv data_meteo.csv data-push/
          cd data-push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Mise à jour quotidienne des CSV" || echo "Rien à committer"
          git push
