name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          miniforge-variant: Mambaforge
          auto-update-conda: true

      - name: Installer eccodes via conda
        run: |
          conda install -c conda-forge eccodes -y

      - name: Ajouter conda/bin au PATH
        run: echo "/usr/share/miniconda/Library/bin" >> $GITHUB_PATH

      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev libproj-dev libgeos-dev libudunits2-dev \
            libpng-dev

      - name: Installer copernicusmarine
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine

      - name: Installer les packages R
        run: |
          Rscript -e "install.packages(c(
            'reticulate','terra','tidyr',
            'httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite'
          ), repos='https://cloud.r-project.org')"

      - name: Exécuter le script R
        env:
          CMEMS_USER:      ${{ secrets.CMEMS_USER }}
          CMEMS_PWD:       ${{ secrets.CMEMS_PWD }}
          DATA_PUSH_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
          PATH:            /usr/share/miniconda/Library/bin:${{ env.PATH }}
        run: Rscript script3.R

      - name: Commit des fichiers CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Ajout automatique des CSV" || echo "Rien à committer"
          git push

      - name: Push vers maree-donnees
        run: |
          git clone https://x-access-token:${{ secrets.DATA_PUSH_TOKEN }}@github.com/ahulin/maree-donnees.git data-push
          cp zos_points.csv data-meteo.csv data-push/
          cd data-push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv
          git commit -m "Mise à jour des CSV" || echo "Rien à committer"
          git push
