jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt avec droits push
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Miniconda + eccodes
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-name: r-env
          activate-environment: r-env
          channels: conda-forge
          packages: eccodes

      - name: Installer les dépendances système pour R
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Installer les dépendances système pour terra
        run: |
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev

      - name: Installer les packages Python nécessaires
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine

      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(c('reticulate','terra','tidyr','httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite'), repos = 'https://cloud.r-project.org')"

      - name: Exécuter le script R
        env:
          CMEMS_USER: ${{ secrets.CMEMS_USER }}
          CMEMS_PWD: ${{ secrets.CMEMS_PWD }}
          DATA_PUSH_TOKEN: ${{ secrets.DATA_PUSH_TOKEN }}
        run: Rscript script3.R
