name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- R + cache CRAN ---
      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Cache bibliothèque R
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('script3.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(
            c('reticulate','terra','tidyr','httr','rvest','ncdf4','raster','dplyr','stringr','jsonlite'),
            repos='https://cloud.r-project.org'
          )"

      # --- Python + cache pip ---
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installer les packages Python nécessaires
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine

      # --- Miniconda + eccodes + PATH ---
      - name: Installer Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: false
          python-version: "3.10"
          channels: conda-forge

      - name: Installer eccodes via conda
        run: conda install -c conda-forge eccodes -y

      - name: Ajouter eccodes au PATH global
        run: echo "/usr/share/miniconda/Library/bin" >> $GITHUB_PATH

      # --- Dépendances système pour terra (GDAL…) et PNG ---
      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev libproj-dev libgeos-dev libudunits2-dev libpng-dev

      # --- Exécution finale ---
      - name: Exécuter le script R
        env:
          CMEMS_USER: ${{ secrets.CMEMS_USER }}
          CMEMS_PWD:  ${{ secrets.CMEMS_PWD }}
        run: Rscript script3.R

      # --- Commit & push CSV ---
      - name: Commit des CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv || echo "rien à committer"
          git commit -m "Mise à jour automatique"  || echo "pas de modifications"
          git push

      - name: Push vers dépôt privé
        run: |
          git clone https://x-access-token:${{ secrets.DATA_PUSH_TOKEN }}@github.com/ahulin/maree-donnees.git data-push
          cp zos_points.csv data_meteo.csv data-push/
          cd data-push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add zos_points.csv data_meteo.csv || echo "rien à committer"
          git commit -m "Mise à jour quotidienne" || echo "pas de modifications"
          git push
