name: Script quotidien marée et météo

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Installer R
        uses: r-lib/actions/setup-r@v2

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances système pour R
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Installer les packages Python nécessaires
        run: |
          python -m pip install --upgrade pip
          pip install copernicusmarine
          
      - name: Installer les dépendances système pour terra
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev
      - name: Installer les packages R nécessaires
        run: |
          Rscript -e "install.packages(c('reticulate','terra'), repos = 'https://cloud.r-project.org')"

      - name: Exécuter le script R
        env:
          CMEMS_USER: ${{ secrets.CMEMS_USER }}
          CMEMS_PWD: ${{ secrets.CMEMS_PWD }}
        run: Rscript script.R

      - name: Commit du fichier CSV généré
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add zos_points.csv
          git commit -m "Ajout automatique du CSV avec les hauteurs de mer" || echo "Aucun changement à committer"
          git push
